name: build

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:

env:
  IMAGE_NAME: steled/sftp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper signature verification
          submodules: true # for shunit2

#      - name: Run ShellCheck
#        uses: ludeeus/action-shellcheck@master
#        with:
#          ignore: tests/shunit2

      - name: Docker meta - debian
        id: meta_debian
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}:debian
          labels: |
            org.opencontainers.image.source=${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}
            org.opencontainers.image.revision=${{ GITHUB_SHA }}
            org.opencontainers.image.created=$(date --rfc-3339=seconds)
          tags: |
            latest
            debian

      - name: Docker meta - alpine
        id: meta_alpine
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}:alpine
          labels: |
            org.opencontainers.image.source=${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}
            org.opencontainers.image.revision=${{ GITHUB_SHA }}
            org.opencontainers.image.created=$(date --rfc-3339=seconds)
          tags: |
            alpine

      - name: Build debian image
        run: |
          docker build . \
            --pull=true \
            --file=Dockerfile \
            --tag="${{ env.IMAGE_NAME }}:latest" \
            --tag="${{ env.IMAGE_NAME }}:debian" \
            --label="org.opencontainers.image.source=${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}" \
            --label="org.opencontainers.image.revision=${{ GITHUB_SHA }}" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Test debian image
        run: tests/run ${{ env.IMAGE_NAME }}:debian

      - name: Build alpine image
        run: |
          docker build . \
            --pull=true \
            --file=Dockerfile-alpine \
            --tag="${{ env.IMAGE_NAME }}:alpine" \
            --label="org.opencontainers.image.source=${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}" \
            --label="org.opencontainers.image.revision=${{ GITHUB_SHA }}" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Test alpine image
        run: tests/run ${{ env.IMAGE_NAME }}:alpine

#      - name: Verify signature
#        if: github.ref == 'refs/heads/master'
#        uses: atmoz/git-verify-ref@master
#        with:
#          import-github-users: atmoz  

      - name: Login to Dockerhub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push - debian
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          labels: ${{ steps.meta_debian.outputs.labels }}
          tags: ${{ steps.meta_debian.outputs.tags }}
            

      - name: Build and push - alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-alpine
          push: true
          labels: ${{ steps.meta_alpine.outputs.labels }}
          tags: ${{ steps.meta_alpine.outputs.tags }}

#      - name: Push images to Docker Hub registry
#        if: github.ref == 'refs/heads/master'
#        run: |
#          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login \
#            -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

#          docker push $IMAGE_NAME # no tags specified to include all tags
#          docker logout

#      - name: Push images to GitHub registry
#        if: github.ref == 'refs/heads/master'
#        run: |
#          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com \
#            -u ${{ github.actor }} --password-stdin

#          TAG_DEBIAN=docker.pkg.github.com/$GITHUB_REPOSITORY/debian
#          TAG_ALPINE=docker.pkg.github.com/$GITHUB_REPOSITORY/alpine
#          docker tag $IMAGE_NAME:debian $TAG_DEBIAN
#          docker tag $IMAGE_NAME:alpine $TAG_ALPINE
#          docker push $TAG_DEBIAN
#          docker push $TAG_ALPINE
#          docker logout docker.pkg.github.com

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and publish debian arm64 images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            steled/sftp:debian-arm64
            steled/sftp:latest-arm64
      - name: Build and publish alpine arm64 images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-alpine
          platforms: linux/arm64
          push: true
          tags: |
             steled/sftp:alpine-arm64